version: '3'
services:
  # MYSQL
  mysql:
    image: mysql:5.6
    container_name: java_mysql
    ports:
      - "9999:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: java_test
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password